name: Auto Test

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "source/_drafts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 切换到当前分支
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: 恢复文件修改时间
        run: |
          git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
      - name: 安装PNPM
        uses: pnpm/action-setup@v4
      - name: 设置Node版本和缓存
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - name: 安装依赖
        run: pnpm install
      - uses: nikeee/setup-pandoc@v1
      - name: 编译应用 🔧
        run: |
          pnpm clean
          pnpm build
          pnpm algolia
        env:
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      - name: 部署应用
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: deploy
          force: false
